name: delivery
description: A new Flutter project.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  analyzer: ^3.3.1
  bloc: ^8.0.3
  cached_network_image: ^3.2.1

  cupertino_icons: ^1.0.2

  dartz: ^0.10.1
  device_preview: ^1.0.0
  dio: ^4.0.6
  equatable: ^2.0.3

  flash: ^2.0.3+3
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1

  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.0+1
  flutter_svg: ^0.22.0
  freezed: ^1.1.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  json_serializable: ^6.1.4
  lottie: ^1.2.2
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sizer: ^2.0.15


dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3

  retrofit_generator: ^4.0.1


# flutter packages pub run build_runner watch --delete-conflicting-outputs
flutter:

  generate: true
  uses-material-design: true

  assets:
#    - assets/images/
#    - assets/images/utils/
#    - assets/images/empty_view/
#    - assets/images/payment/
#    - assets/images/social/
#    - assets/images/navbar/
#    - assets/images/moreicons/
#    - assets/images/map/
#    - assets/images/fooderror/
    - assets/json/
#
#  fonts:
#    - family: Metropolis
#      fonts:
#        - asset: assets/fonts/metropolis/Metropolis-ExtraBold.otf
#          weight: 800
#        - asset: assets/fonts/metropolis/Metropolis-Black.otf
#          weight: 900
#        - asset: assets/fonts/metropolis/Metropolis-Bold.otf
#          weight: 700
#        - asset: assets/fonts/metropolis/Metropolis-SemiBold.otf
#          weight: 600
#        - asset: assets/fonts/metropolis/Metropolis-Medium.otf
#          weight: 500
#        - asset: assets/fonts/metropolis/Metropolis-Regular.otf
#          weight: 400
#        - asset: assets/fonts/metropolis/Metropolis-Light.otf
#          weight: 300
#        - asset: assets/fonts/metropolis/Metropolis-ExtraLight.otf
#          weight: 200
#    - family: Rubik
#      fonts:
#        - asset: assets/fonts/rubik/Rubik-ExtraBold.ttf
#          weight: 800
#        - asset: assets/fonts/rubik/Rubik-Black.ttf
#          weight: 900
#        - asset: assets/fonts/rubik/Rubik-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/rubik/Rubik-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/rubik/Rubik-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/rubik/Rubik-Light.ttf
#          weight: 300
#    - family: Tajawal
#      fonts:
#        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
#          weight: 800
#        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
#          weight: 900
#        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
#          weight: 200
#        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
#          weight: 300
flutter_intl:
  enabled: true

#flutter_native_splash:
#
#  color: "#ffffff"
#  image: assets/images/logo.png
#  android_12:
#    image: assets/images/logo.png
#    color: "#ffffff"
#
#  android: true
#  ios: true
#  #web: false
